import notApi from '../assets/images/API_ICON.png'

export const bookings = [
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: "API",
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPaxName: "Rahul Sharma",
        leadPax: "M",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Boat",
        status: "Confirmed",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: "API",
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "M",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Car",
        status: "Confirmed",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: notApi,
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "A",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Boat",
        status: "Confirmed",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: notApi,
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "A",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Car",
        status: "Confirmed",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: "API",
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "M",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Boat",
        status: "Cancelled",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: "API",
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "M",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Car",
        status: "Cancelled",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: notApi,
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "M",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Car",
        status: "Vouchered",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: notApi,
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "M",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Boat",
        status: "Vouchered",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: "API",
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "A",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Boat",
        status: "Vouchered",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: "API",
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "A",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Car",
        status: "Vouchered",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },

    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: "",
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "M",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Boat",
        status: "Travelled",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
    {
        id: `AB_US_001`,
        agent: "ABC Pvt. Ltd.",
        manager: "Drishti Yadav",
        source: "",
        date: "03-02-2025",
        travelDate: "03-02-2025",
        leadPaxName: "Rahul Sharma",
        leadPax: "M",
        paxDetails: "2A, 2C (6yrs, 8yrs)",
        type: "Car",
        status: "Travelled",
        // status: ["Confirmed", "Cancelled", "Vouchered", "Travelled"][idx % 4],
        city: "Melbourne",
        product: "Airport Transfer",
        productDetails: 'IGI to South delhi'
    },
]


export const TableHeader = [
    { key: "Booking Status", width: '20px' },
    { key: "Agent", width: '269px' },
    { key: "Booking Source", width: '5px' },
    { key: "Booking ID", width: '30px' },
    { key: "Booking Date", width: '60px' },
    { key: "Travel Date", width: '95px' },
    { key: "Lead Pax Name", width: '50px' },
    { key: "Product Type", width: '30px' },
    { key: "Booking Status", width: '30px' },
    { key: "Product City", width: '50px' },
    { key: "Name", width: '250px' }
]